apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-template.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm-template.labels" . | nindent 4}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "helm-template.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "helm-template.name" . }}
    spec:
      containers:
        - name: fastapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          volumes:
            - name:
              
